/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.VendaController;
import DAO.ClienteDAO;
import DAO.ProdutoDAO;
import DAO.VendaDAO;
import Model.Cliente;
import Model.Produto;
import Model.Venda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matheus.Caetano
 */
public class ViewFormularioVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCarrinhoCompra
     */
    public ViewFormularioVenda() {
        initComponents();
        rodarvenda=0;
        retorno =0;
        // pega data do sistema e passa para o campo data do formulario
 SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyy");
 Date hoje = new Date();
 txtData.setText(df.format(hoje));
    }
    
    int flag; // variavel para controlar as acoes depois do clique na tabela pesquisa
    int codvenda; // variavel para armazenar codigo da venda
    int rodarvenda; // variavel para controler abertura de vendas
    int retorno; // variavel para retornar o id da venda
    double total; // variavel para manipular o total das vendas
    Venda venda = new Venda(); // instaciando objeto venda
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        btnbuscaproduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        btnbuscacpf = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorItem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrinho = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPesquisa = new javax.swing.JTable();
        txtValorTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labelcod = new javax.swing.JLabel();
        labelestoque = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Venda");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Formulario de Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("CPF Cliente:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Data Venda:");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtData.setEnabled(false);
        txtData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataFocusGained(evt);
            }
        });
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        btnbuscaproduto.setText("Buscar");
        btnbuscaproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaprodutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto:");

        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });

        btnbuscacpf.setText("Buscar");
        btnbuscacpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscacpfActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade:");

        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusGained(evt);
            }
        });
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor p/ Unidade:");

        tblCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCarrinho);

        jLabel8.setText("Tabela de Pesquisa:");

        jLabel9.setText("Carrinho do Cliente:");

        tblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPesquisa);

        jLabel7.setText("Valor Total:");

        jButton2.setText("Cancelar Venda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Finalizar Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        labelcod.setText("jLabel10");

        labelestoque.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnbuscacpf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(88, 88, 88))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(txtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelcod, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(labelestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(133, 133, 133)))
                                .addComponent(btnbuscaproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(labelcod, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscacpf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscaproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscaprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaprodutoActionPerformed
        flag = 2;
        rodarvenda=rodarvenda+1;
        
        if(rodarvenda<2){
        retorno = VendaController.Criandovenda(0);
        if (retorno != 0){
            System.out.println("Venda aberta com sucesso!");
        }
        
        else{
            System.out.println("Falha ao abrir venda!");
        }
        }
        
        
        codvenda = retorno;
        if(txtProduto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome do produto para realizar a pesquisa");
        }
        else{
        ArrayList<Produto> listaProduto = ProdutoDAO.consultarProdutopornome(txtProduto.getText());
        if(listaProduto.size()>0){
        DefaultTableModel tmPesquisar = new DefaultTableModel()
                         {
                    @Override
                    public boolean isCellEditable(final int row, final int column) {
                            return false;
                    }
            };
        tmPesquisar.addColumn("Id_Produto");
        tmPesquisar.addColumn("Nome");
        tmPesquisar.addColumn("Valor");
        tmPesquisar.addColumn("Qntd. Estoque");
       

        tblPesquisa.setModel(tmPesquisar);

        //Removo a coluna ID da View (JTable) mas mantenho na model para armazenar o ID
        // tblMaquina.removeColumn(tblMaquina.getColumnModel().getColumn(0));

        //Limpo a tabela, excluindo todas as linhas para depois mostrar os dados novamente
        tmPesquisar.setRowCount(0);

        //Para cada cliente resgatado do banco de dados, atualizo a tabela
        for (Produto p : listaProduto) {
            tmPesquisar.addRow(new Object[]{p.getIdProduto(),p.getProduto(),p.getPreco(), p.getEstoque()});
        }
        //Defino o tamanho para cada coluna
        //tblClientes.getColumnModel().getColumn(0).setPreferredWidth(50); //ID
        tblPesquisa.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblPesquisa.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblPesquisa.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblPesquisa.getColumnModel().getColumn(3).setPreferredWidth(100);
        } else{
            JOptionPane.showMessageDialog(this,"Produto não encontrado");
        }
       }  
    }//GEN-LAST:event_btnbuscaprodutoActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed

    }//GEN-LAST:event_txtDataActionPerformed

    private void btnbuscacpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscacpfActionPerformed
        flag = 1; // atualizo a variavel flag para conseguir atualizar os campos e as labels
        if(txtCPF.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(this,"Digite um CPF para realizar a busca");
        }
        else{
        String cpfnormal = txtCPF.getText().replace(".", "").replace("-", ""); // pego o que estiver mo campo txtCPF, apenas numeros
        
        ArrayList<Cliente> listaCliente = ClienteDAO.consultarClienteporCPF(cpfnormal);// chamo metodo diretamente da DAO que realiza pesquisa e retorna a lista atualizada referente a pesquisa
       if(listaCliente.size()>0){
        // crio um novo modelo de tabela
        DefaultTableModel tmPesquisa = new DefaultTableModel()
                         {
                    @Override
                    public boolean isCellEditable(final int row, final int column) {
                            return false;
                    }
            };
        tmPesquisa.addColumn("Id_Cliente");
        tmPesquisa.addColumn("Nome");
        tmPesquisa.addColumn("CPF");
        
        
        //Adiciono este novo modelo a tabela pesquisa
        tblPesquisa.setModel(tmPesquisa);


        //Limpo a tabela, excluindo todas as linhas para depois mostrar os dados novamente
        tmPesquisa.setRowCount(0);

        //Para cada cliente resgatado do banco de dados, atualizo a tabela
        for (Cliente c : listaCliente) {
            tmPesquisa.addRow(new Object[]{c.getIdCliente(),c.getNome(),c.getCPFSomenteNumeros()});
        }
        //Defino o tamanho para cada coluna
        tblPesquisa.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblPesquisa.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblPesquisa.getColumnModel().getColumn(2).setPreferredWidth(100);
       }else{
          JOptionPane.showMessageDialog(this,"Cliente não encontrado");
       }
       }  
    }//GEN-LAST:event_btnbuscacpfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
      Venda venda = new Venda(); // instancio um novo obejto da classeModel -> venda
      venda.setData(txtData.getText()); // Atualizo os parametros desta classe ->Data
      venda.setValorVenda(Double.parseDouble(txtValorTotal.getText()));// Atualizo os parametros desta classe ->Valor total da Venda
      venda.setCpfCliente(txtCPF.getText().replace(".", "").replace("-", ""));// Atualizo os parametros desta classe ->Cpf do cliente
      venda.setIdVenda(codvenda);// Atualizo o codigo da venda para conseguir realizar o cadstro da mesma
      
     
      boolean retorno = VendaController.PopulandoVenda(venda); // chamo umdos metodos do pacote Controller que serve para adicionar os itens na venda
      if(retorno==true){
          JOptionPane.showMessageDialog(null,"Venda Realizada com Sucesso!");//feedback
          dispose();//apos a venda ser cadastrada em sistema, fechar o formulario
      }
      else{
          JOptionPane.showMessageDialog(null,"Falha ao finalizar Venda!");//feedback
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        
        boolean retorno = VendaController.CancelarVenda();// chamo metodo da aba controller para realizar  cancelamento das vendas em que a venda nao foi concluida e que nao possui itens.
      if(retorno==true){
          JOptionPane.showMessageDialog(null,"Venda Cancelada com sucesso!");//feedback
          dispose();// apos cancelamento fecho o formulario de vendas
      }
      else{
          JOptionPane.showMessageDialog(null,"Falha ao Cancelar Venda!");//feedback
      }
        dispose();//apos realizar ou nao o cancelmento fecho o relatorio
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Código da venda:"+codvenda);testes
        //System.out.println("Codigo do produto:"+labelcod.getText());testes
        //System.out.println("ESTOQUE:"+labelestoque.getText());testes
       if(labelestoque.getText().equals("jLabel10") || txtCPF.getText().equals("") ){
           JOptionPane.showMessageDialog(this,"Para realizar o processo de venda, é necessario um cliente e um produto selecionado. Por favor Confira se os dois estao selecionados");
       }
       
       else{
     // verificando se o produto tem estoque para realizar venda
     if(Integer.parseInt(labelestoque.getText())>=Integer.parseInt(txtQuantidade.getText()))
     {
     //se permitiu a venda realizar o decremento e armazenas na variavel para decrementarmos diretamento do BD
     int estoque_sobrou=Integer.parseInt(labelestoque.getText()) - Integer.parseInt(txtQuantidade.getText());
     //adicionando item no carrinho
    // atulizo os onjetos da classe Venda para conseguir realizar a diacao do produto no carrinho
      Venda venda = new Venda();
      venda.setCpfCliente(txtCPF.getText().replace(".", "").replace("-", ""));
      venda.setNomeProduto(txtProduto.getText());
      venda.setQtdItem(Integer.parseInt(txtQuantidade.getText()));
      venda.setCodProduto(Integer.parseInt(labelcod.getText()));
      venda.setIdVenda(codvenda);
      venda.setEstoque(estoque_sobrou);
     
      boolean retorno = VendaController.Criandoitemporvenda(venda);
      
        if (retorno == true){
            // atualizar a planilha de pesquisa
            ArrayList<Produto> listaProduto = ProdutoDAO.consultarProdutopornome(txtProduto.getText());

        DefaultTableModel tmPesquisar = new DefaultTableModel()
                         {
                    @Override
                    public boolean isCellEditable(final int row, final int column) {
                            return false;
                    }
            };
        tmPesquisar.addColumn("Id_Produto");
        tmPesquisar.addColumn("Nome");
        tmPesquisar.addColumn("Valor");
        tmPesquisar.addColumn("Qntd. Estoque");
       

        tblPesquisa.setModel(tmPesquisar);

        //Limpo a tabela, excluindo todas as linhas para depois mostrar os dados novamente
        tmPesquisar.setRowCount(0);

        //Para cada produto resgatado do banco de dados, atualizo a tabela
        for (Produto p : listaProduto) {
            tmPesquisar.addRow(new Object[]{p.getIdProduto(),p.getProduto(),p.getPreco(), p.getEstoque()});
        }
        //Defino o tamanho para cada coluna
       
        tblPesquisa.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblPesquisa.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblPesquisa.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblPesquisa.getColumnModel().getColumn(3).setPreferredWidth(100);
            
        }
        
        else{
            JOptionPane.showMessageDialog(null,"Falha ao colocar item no carrinho!");
        }
        
       
       //adicionar no carrinho
       ArrayList<Venda> carregaritensvenda = VendaDAO.Carregaritensvenda(codvenda);
        
        DefaultTableModel tmCarrinho = new DefaultTableModel()
                         {
                    @Override
                    public boolean isCellEditable(final int row, final int column) {
                            return false;
                    }
            };
        tmCarrinho.addColumn("Produto");
        tmCarrinho.addColumn("Quantidade");
        tmCarrinho.addColumn("Total");
        
        

        tblCarrinho.setModel(tmCarrinho);

        
        tmCarrinho.setRowCount(0);
        
        for (Venda v : carregaritensvenda) {
            int quantidadeaservendida = v.getQtdItem();
            double valordoproduto = v.getvalorunitario();
            
            tmCarrinho.addRow(new Object[]{v.getNomeProduto(),v.getQtdItem(),""+quantidadeaservendida*valordoproduto});
        }
        //Defino o tamanho para cada coluna
       
        tblCarrinho.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblCarrinho.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblCarrinho.getColumnModel().getColumn(2).setPreferredWidth(100);
        
        
        
        
        
        double total = VendaDAO.Realizarsoma(codvenda);
        txtValorTotal.setText(Double.toString(total));
      }
     else{
         JOptionPane.showMessageDialog(null,"Produto com estoque insuficiente!");
     }
     
     }
    }//GEN-LAST:event_jButton3ActionPerformed
 
    private void tblPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesquisaMouseClicked
        // TODO add your handling code here:
        if(flag==1){
            String cpf_cliente = "" + tblPesquisa.getValueAt(tblPesquisa.getSelectedRow(),2);
            txtCPF.setText(cpf_cliente);
        }
        else{
            String id_produto = "" + tblPesquisa.getValueAt(tblPesquisa.getSelectedRow(),0);//tirando valores da tabela e mudando textfields
            String nome_produto = "" + tblPesquisa.getValueAt(tblPesquisa.getSelectedRow(),1);//tirando valores da tabela e mudando textfields
            String precounitario = "" + tblPesquisa.getValueAt(tblPesquisa.getSelectedRow(),2);//tirando valores da tabela e mudando textfields
            String quantidadeestoque = "" + tblPesquisa.getValueAt(tblPesquisa.getSelectedRow(),3);//tirando valores da tabela e mudando textfields
            txtValorItem.setText(precounitario);// alterando os textfields
            txtProduto.setText(nome_produto);// alterando os textfields
            txtQuantidade.setText("1");// alterando os textfields
            labelcod.setText(id_produto);// alterando os textfields
            labelestoque.setText(quantidadeestoque);// alterando os textfields
        }
    }//GEN-LAST:event_tblPesquisaMouseClicked

    private void txtQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusGained
    
    }//GEN-LAST:event_txtQuantidadeFocusGained

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFocusGained
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txtDataFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscacpf;
    private javax.swing.JButton btnbuscaproduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelcod;
    private javax.swing.JLabel labelestoque;
    private javax.swing.JTable tblCarrinho;
    private javax.swing.JTable tblPesquisa;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorItem;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
