/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Matheus.Caetano
 */
public class ViewFuncionarioDesktop extends javax.swing.JFrame {

    /**
     * Creates new form ViewFuncionarioDesktop
     */
    public ViewFuncionarioDesktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopFuncionario = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnFnDesktopFile = new javax.swing.JMenu();
        MnFnDesktopSair = new javax.swing.JMenuItem();
        MnFnDesktopNavegador = new javax.swing.JMenu();
        MnFnDesktopCadastrar = new javax.swing.JMenuItem();
        MnFnDesktopGestao = new javax.swing.JMenuItem();
        MnFnDesktopNavegador1 = new javax.swing.JMenu();
        MnFnDesktopCadastrar1 = new javax.swing.JMenuItem();
        MnFnDesktopGestao1 = new javax.swing.JMenuItem();
        MnFnDesktopProduto = new javax.swing.JMenu();
        MnFnDesktopCadastrarProduto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnFnDesktopRelatorio = new javax.swing.JMenu();
        MnFnDesktopVenda = new javax.swing.JMenuItem();
        MnFnDesktopRelatorioMensal = new javax.swing.JMenuItem();
        MnFnDesktopSobre = new javax.swing.JMenu();
        MnFnDesktopCriadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopFuncionarioLayout = new javax.swing.GroupLayout(DesktopFuncionario);
        DesktopFuncionario.setLayout(DesktopFuncionarioLayout);
        DesktopFuncionarioLayout.setHorizontalGroup(
            DesktopFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        DesktopFuncionarioLayout.setVerticalGroup(
            DesktopFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );

        MnFnDesktopFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file-icon.png"))); // NOI18N
        MnFnDesktopFile.setText("Arquivo");

        MnFnDesktopSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MnFnDesktopSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit-icon.png"))); // NOI18N
        MnFnDesktopSair.setText("Sair");
        MnFnDesktopSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopSairActionPerformed(evt);
            }
        });
        MnFnDesktopFile.add(MnFnDesktopSair);

        jMenuBar1.add(MnFnDesktopFile);

        MnFnDesktopNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionario-icon.png"))); // NOI18N
        MnFnDesktopNavegador.setText("Funcionário");

        MnFnDesktopCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/person-edit-icon.png"))); // NOI18N
        MnFnDesktopCadastrar.setText("Cadastrar Funcionario");
        MnFnDesktopCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopCadastrarActionPerformed(evt);
            }
        });
        MnFnDesktopNavegador.add(MnFnDesktopCadastrar);

        MnFnDesktopGestao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio-mensal-icon.png"))); // NOI18N
        MnFnDesktopGestao.setText("Gestão de Funcionários");
        MnFnDesktopGestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopGestaoActionPerformed(evt);
            }
        });
        MnFnDesktopNavegador.add(MnFnDesktopGestao);

        jMenuBar1.add(MnFnDesktopNavegador);

        MnFnDesktopNavegador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente-icon.png"))); // NOI18N
        MnFnDesktopNavegador1.setText("Cliente");

        MnFnDesktopCadastrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/person-edit-icon.png"))); // NOI18N
        MnFnDesktopCadastrar1.setText("Cadastrar Cliente");
        MnFnDesktopCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopCadastrar1ActionPerformed(evt);
            }
        });
        MnFnDesktopNavegador1.add(MnFnDesktopCadastrar1);

        MnFnDesktopGestao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio-mensal-icon.png"))); // NOI18N
        MnFnDesktopGestao1.setText("Gestão de Clientes");
        MnFnDesktopGestao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopGestao1ActionPerformed(evt);
            }
        });
        MnFnDesktopNavegador1.add(MnFnDesktopGestao1);

        jMenuBar1.add(MnFnDesktopNavegador1);

        MnFnDesktopProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto-icon.png"))); // NOI18N
        MnFnDesktopProduto.setText("Produto");

        MnFnDesktopCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brinquedo-icon.png"))); // NOI18N
        MnFnDesktopCadastrarProduto.setText("Cadastrar Produto");
        MnFnDesktopCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopCadastrarProdutoActionPerformed(evt);
            }
        });
        MnFnDesktopProduto.add(MnFnDesktopCadastrarProduto);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio-mensal-icon.png"))); // NOI18N
        jMenuItem1.setText("Gestão dos Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnFnDesktopProduto.add(jMenuItem1);

        jMenuBar1.add(MnFnDesktopProduto);

        MnFnDesktopRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loja-icon.png"))); // NOI18N
        MnFnDesktopRelatorio.setText("Venda");

        MnFnDesktopVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho-icon.png"))); // NOI18N
        MnFnDesktopVenda.setText("Venda");
        MnFnDesktopVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopVendaActionPerformed(evt);
            }
        });
        MnFnDesktopRelatorio.add(MnFnDesktopVenda);

        MnFnDesktopRelatorioMensal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio-icon.png"))); // NOI18N
        MnFnDesktopRelatorioMensal.setText("Relatório Vendas");
        MnFnDesktopRelatorioMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopRelatorioMensalActionPerformed(evt);
            }
        });
        MnFnDesktopRelatorio.add(MnFnDesktopRelatorioMensal);

        jMenuBar1.add(MnFnDesktopRelatorio);

        MnFnDesktopSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/info-icon.png"))); // NOI18N
        MnFnDesktopSobre.setText("Sobre");

        MnFnDesktopCriadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/team-icon.png"))); // NOI18N
        MnFnDesktopCriadores.setText("Sobre os Criadores");
        MnFnDesktopCriadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFnDesktopCriadoresActionPerformed(evt);
            }
        });
        MnFnDesktopSobre.add(MnFnDesktopCriadores);

        jMenuBar1.add(MnFnDesktopSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopFuncionario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnFnDesktopSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopSairActionPerformed
        ViewFuncionarioDesktop.this.dispose();
    }//GEN-LAST:event_MnFnDesktopSairActionPerformed

    private void MnFnDesktopGestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopGestaoActionPerformed
        ViewGestaoFuncionarios viewFuncionarioAltera = new ViewGestaoFuncionarios();
        DesktopFuncionario.add(viewFuncionarioAltera);
        viewFuncionarioAltera.setVisible(true);
    }//GEN-LAST:event_MnFnDesktopGestaoActionPerformed

    private void MnFnDesktopCriadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopCriadoresActionPerformed
        new ViewCriadores().setVisible(true);
    }//GEN-LAST:event_MnFnDesktopCriadoresActionPerformed

    private void MnFnDesktopVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopVendaActionPerformed
      ViewFormularioVenda viewFormulariovenda = new ViewFormularioVenda();
        DesktopFuncionario.add(viewFormulariovenda);
        viewFormulariovenda.setVisible(true);  
    }//GEN-LAST:event_MnFnDesktopVendaActionPerformed

    private void MnFnDesktopRelatorioMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopRelatorioMensalActionPerformed
       ViewRelatorioVenda viewRelatoriovenda = new ViewRelatorioVenda();
        DesktopFuncionario.add(viewRelatoriovenda);
        viewRelatoriovenda.setVisible(true);  
    }//GEN-LAST:event_MnFnDesktopRelatorioMensalActionPerformed

    private void MnFnDesktopCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopCadastrarProdutoActionPerformed
        ViewProdutoCadastrar viewProdutoCadastrar = new ViewProdutoCadastrar();
        DesktopFuncionario.add(viewProdutoCadastrar);
        viewProdutoCadastrar.setVisible(true);
    }//GEN-LAST:event_MnFnDesktopCadastrarProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViewGestaoProdutos viewProdutoAlterar = new ViewGestaoProdutos();
        DesktopFuncionario.add(viewProdutoAlterar);
        viewProdutoAlterar.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MnFnDesktopCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopCadastrarActionPerformed
        ViewFuncionarioCadastrar viewFuncionarioCadastrar = new ViewFuncionarioCadastrar();// colocando o tela dentro do painel
        DesktopFuncionario.add(viewFuncionarioCadastrar);
        viewFuncionarioCadastrar.setVisible(true);
        
    }//GEN-LAST:event_MnFnDesktopCadastrarActionPerformed

    private void MnFnDesktopCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopCadastrar1ActionPerformed
        ViewClienteCadastrar viewClienteCadastrar = new ViewClienteCadastrar();
        DesktopFuncionario.add(viewClienteCadastrar);
        viewClienteCadastrar.setVisible(true);
    }//GEN-LAST:event_MnFnDesktopCadastrar1ActionPerformed

    private void MnFnDesktopGestao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFnDesktopGestao1ActionPerformed
        // TODO add your handling code here:
        ViewGestaoCliente viewGestaoCliente = new ViewGestaoCliente();
        DesktopFuncionario.add(viewGestaoCliente);
        viewGestaoCliente.setVisible(true);
    }//GEN-LAST:event_MnFnDesktopGestao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarioDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarioDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarioDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarioDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFuncionarioDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopFuncionario;
    private javax.swing.JMenuItem MnFnDesktopCadastrar;
    private javax.swing.JMenuItem MnFnDesktopCadastrar1;
    private javax.swing.JMenuItem MnFnDesktopCadastrarProduto;
    private javax.swing.JMenuItem MnFnDesktopCriadores;
    private javax.swing.JMenu MnFnDesktopFile;
    private javax.swing.JMenuItem MnFnDesktopGestao;
    private javax.swing.JMenuItem MnFnDesktopGestao1;
    private javax.swing.JMenu MnFnDesktopNavegador;
    private javax.swing.JMenu MnFnDesktopNavegador1;
    private javax.swing.JMenu MnFnDesktopProduto;
    private javax.swing.JMenu MnFnDesktopRelatorio;
    private javax.swing.JMenuItem MnFnDesktopRelatorioMensal;
    private javax.swing.JMenuItem MnFnDesktopSair;
    private javax.swing.JMenu MnFnDesktopSobre;
    private javax.swing.JMenuItem MnFnDesktopVenda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

   
}
