/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FuncionarioController;
import Model.Funcionario;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author MOISES
 */
public class ViewFuncionarioCadastrar extends javax.swing.JInternalFrame {
  String modotela = "Criacao";
  Funcionario objFuncionario;
    /**
     * Creates new form ViewFuncionarioCadastrar
     */
    public ViewFuncionarioCadastrar() {
        initComponents();
        objFuncionario = new Funcionario();
        
    }
    
    public ViewFuncionarioCadastrar(Funcionario pFuncionario){
        initComponents();
        this.objFuncionario = pFuncionario;
         System.out.println("..........Iniciou View Cadastrar............");
        System.out.println("ID:"+pFuncionario.getIdFuncionario());
        System.out.println("Nome:"+pFuncionario.getNome());
        System.out.println("cpf:"+pFuncionario.getCPF());
        System.out.println("Sexo:"+pFuncionario.getSexo());
        System.out.println("Email:"+pFuncionario.getEmail());
        System.out.println("Telefone:"+pFuncionario.getTelefone());
        System.out.println("Cargo:"+pFuncionario.getCargo());
        System.out.println("Salario:"+pFuncionario.getSalario());
        
        
        this.txtFnCadastroNome.setText(pFuncionario.getNome());
        this.txtFnCadastroCpf.setText(pFuncionario.getCPFSomenteNumeros());
        this.txtSexo.setText(pFuncionario.getSexo());
        this.txtFnCadastroEmail.setText(pFuncionario.getEmail());
        this.txtTelefone.setText(pFuncionario.getTelefone());
        this.txtCargo.setText(pFuncionario.getCargo());
        this.txtSalario.setText(Double.toString(pFuncionario.getSalario()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gruposexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFnCadastroNome = new javax.swing.JTextField();
        txtFnCadastroEmail = new javax.swing.JTextField();
        txtFnCadastroCpf = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtSexo = new javax.swing.JTextField();
        btnFnCadastroCancelar = new javax.swing.JButton();
        btnFnCadastroSalvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Funcionario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro - Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Nome *:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Cpf *:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Sexo *:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Email *:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Telefone *:");

        txtFnCadastroNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFnCadastroNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroNomeFocusLost(evt);
            }
        });

        txtFnCadastroEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFnCadastroEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroEmailFocusLost(evt);
            }
        });
        txtFnCadastroEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnCadastroEmailActionPerformed(evt);
            }
        });

        try {
            txtFnCadastroCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFnCadastroCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroCpfFocusLost(evt);
            }
        });
        txtFnCadastroCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnCadastroCpfActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Cargo *:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("Sálario *:");

        txtCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCargoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCargoFocusLost(evt);
            }
        });
        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFnCadastroNome, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(txtFnCadastroEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(txtFnCadastroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFnCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFnCadastroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFnCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnFnCadastroCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnFnCadastroCancelar.setText("Cancelar");
        btnFnCadastroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnCadastroCancelarActionPerformed(evt);
            }
        });

        btnFnCadastroSalvar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnFnCadastroSalvar.setText("Cadastrar");
        btnFnCadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnCadastroSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnFnCadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnFnCadastroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFnCadastroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnCadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnCadastroNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroNomeFocusGained
        txtFnCadastroNome.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroNomeFocusGained

    private void txtFnCadastroNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroNomeFocusLost
        if(txtFnCadastroNome.getText().trim().equals("")) {
            txtFnCadastroNome.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroNomeFocusLost

    private void txtFnCadastroEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroEmailFocusGained
        txtFnCadastroEmail.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroEmailFocusGained

    private void txtFnCadastroEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroEmailFocusLost
        if(txtFnCadastroEmail.getText().trim().equals("")) {
            txtFnCadastroEmail.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroEmailFocusLost

    private void txtFnCadastroCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroCpfFocusGained
        txtFnCadastroCpf.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroCpfFocusGained

    private void txtFnCadastroCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroCpfFocusLost
        if(txtFnCadastroCpf.getText().trim().equals("")) {
            txtFnCadastroCpf.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroCpfFocusLost

    private void txtCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCargoFocusGained
        txtCargo.setBackground(Color.white);
    }//GEN-LAST:event_txtCargoFocusGained

    private void txtCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCargoFocusLost
        if(txtCargo.getText().trim().equals("")) {
            txtCargo.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtCargoFocusLost

    private void btnFnCadastroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnCadastroCancelarActionPerformed
        txtFnCadastroNome.setText("");
        txtFnCadastroNome.setBackground(Color.white);

        txtFnCadastroCpf.setText("");
        txtFnCadastroCpf.setBackground(Color.white);

        txtSexo.setText("");
        txtFnCadastroCpf.setBackground(Color.white);

        txtFnCadastroEmail.setText("");
        txtFnCadastroEmail.setBackground(Color.white);

        txtTelefone.setText("");
        txtTelefone.setBackground(Color.white);

        txtCargo.setText("");
        txtCargo.setBackground(Color.white);

        txtSalario.setText("");
        txtSalario.setBackground(Color.white);
        
        this.dispose();

    }//GEN-LAST:event_btnFnCadastroCancelarActionPerformed

    private void btnFnCadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnCadastroSalvarActionPerformed

     if(modotela=="Criacao"){      
     if(txtFnCadastroNome.getText().trim().equals("") || txtFnCadastroCpf.getText().trim().equals("")|| txtSexo.getText().trim().equals("")|| txtFnCadastroEmail.getText().trim().equals("")|| txtTelefone.getText().trim().equals("")|| txtCargo.getText().trim().equals("")|| txtSalario.getText().trim().equals("")){
         //validando as informacoes 
         //validar se o usuario realmente digitou
         JOptionPane.showMessageDialog(null,"Voce esqueceu de um dos valores obrigatórios, Por gentileza Preencher.");
        
    }   
     else{
        //transformando os valores dos campos ems eus determinados valores corretos (tipos)
        String nome = txtFnCadastroNome.getText();
        String CPF = txtFnCadastroCpf.getText();
        String Sexo = txtSexo.getText();
        String email = txtFnCadastroEmail.getText();
        String telefone = txtTelefone.getText();
        String cargo = txtCargo.getText();
        double salario = Double.parseDouble(txtSalario.getText());
         // neste else chamo o Controller
         
         boolean retorno = FuncionarioController.Novo(nome, CPF, Sexo, email, telefone, cargo, salario);
        if (retorno == true){
            JOptionPane.showMessageDialog(null,"Funcionario cadastrado com sucesso!");
        }
        
        else{
            JOptionPane.showMessageDialog(null,"Falha ao cadastrar novo funcionario!");
        
            
        }}
     
         
         
         
             }
     else{
         //edicao
         //TODO: implementar verificação de obrigatoriedade
            
        if(txtFnCadastroNome.getText().trim().equals("") || txtFnCadastroCpf.getText().trim().equals("")|| txtSexo.getText().trim().equals("")|| txtFnCadastroEmail.getText().trim().equals("")|| txtTelefone.getText().trim().equals("")|| txtCargo.getText().trim().equals("")|| txtSalario.getText().trim().equals("")){
         //validando as informacoes 
         //validar se o usuario realmente digitou
         JOptionPane.showMessageDialog(null,"Voce esqueceu de um dos valores obrigatórios, Por gentileza Preencher.");
        
    }   
     else{
        //transformando os valores dos campos ems eus determinados valores corretos (tipos)
       
         objFuncionario.setNome(txtFnCadastroNome.getText());
         objFuncionario.setCPF(txtFnCadastroCpf.getText());
         objFuncionario.setSexo(txtSexo.getText());
         objFuncionario.setEmail(txtFnCadastroEmail.getText());
         objFuncionario.setTelefone(txtTelefone.getText());
         objFuncionario.setCargo(txtCargo.getText());
         objFuncionario.setSalario(Double.parseDouble(txtSalario.getText()));
         
         boolean retorno = FuncionarioController.Alterar(objFuncionario);
        if (retorno == true){
            JOptionPane.showMessageDialog(null,"Funcionario atualizado com sucesso!");
        }
        
        else{
            JOptionPane.showMessageDialog(null,"Falha ao atualizar funcionario!");
            
        }}
                
               
         
         
         
     }
     
     
     
     
    
     
     
    }//GEN-LAST:event_btnFnCadastroSalvarActionPerformed

    private void txtFnCadastroCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnCadastroCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnCadastroCpfActionPerformed

    private void txtFnCadastroEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnCadastroEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnCadastroEmailActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gruposexo;
    private javax.swing.JButton btnFnCadastroCancelar;
    private javax.swing.JButton btnFnCadastroSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JFormattedTextField txtFnCadastroCpf;
    private javax.swing.JTextField txtFnCadastroEmail;
    private javax.swing.JTextField txtFnCadastroNome;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables



   

       
    }
