/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.ProdutoController;
import Model.Produto;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class ViewProdutoCadastrar extends javax.swing.JInternalFrame {
String modotela = "Criacao";
Produto objProduto;
    /**
     * Creates new form ViewProdutoCadastra
     */
    public ViewProdutoCadastrar() {
        initComponents();
        objProduto = new Produto();
    }
    
        public ViewProdutoCadastrar(Produto pProduto){
        initComponents();
        this.objProduto = pProduto;
         
        
        
        this.txtProduto.setText(pProduto.getProduto());
        this.comboCategoria.setSelectedItem(pProduto.getCategoria());
        this.txtValor.setText(Double.toString(pProduto.getPreco()));
        this.txtEstoque.setText(Integer.toString(pProduto.getEstoque()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        btnFnCadastroSalvar = new javax.swing.JButton();
        btnFnCadastroCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Produto - Cadastrar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto - Cadastrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Produto *:");

        txtProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Categoria *:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setText("Quantidade em estoque*:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Valor Unitário*:");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artes e Atividades  ", "Blocos de Montar  ", "Bonecas  ", "Bonecos e Cenários  ", "Carrinhos e Cia  ", "Colecionáveis  ", "Fantasias  ", "Faz de Conta  ", "Instrumentos Musicais  ", "Jogos  ", "Lançadores  ", "Massinhas  ", "Pelúcias  ", "Pistas e Autoramas  ", "Quebra Cabeça", "Bicicletas  ", "Mini Veículos Elétricos  ", "Mini Veículos para Passeio  ", "Patinetes e Skatenets  ", "Patins e Skates  ", "Playgrounds  ", "Praia e Piscina" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEstoque)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnFnCadastroSalvar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnFnCadastroSalvar.setText("Salvar");
        btnFnCadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnCadastroSalvarActionPerformed(evt);
            }
        });

        btnFnCadastroCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnFnCadastroCancelar.setText("Cancelar");
        btnFnCadastroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnCadastroCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(btnFnCadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnFnCadastroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFnCadastroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnCadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFnCadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnCadastroSalvarActionPerformed
    String categoria_verifica = (String)comboCategoria.getSelectedItem();
        if(modotela=="Criacao"){
            if(txtProduto.getText().trim().equals("") || categoria_verifica.equals("")|| txtValor.getText().trim().equals("")|| txtEstoque.getText().trim().equals("")){
                //validando as informacoes
                //validar se o usuario realmente digitou
                JOptionPane.showMessageDialog(null,"Voce esqueceu de um dos valores obrigatórios, Por gentileza Preencher.");

            }
            else{
                //transformando os valores dos campos ems eus determinados valores corretos (tipos)
                String produto = txtProduto.getText();
                String categoria = (String)comboCategoria.getSelectedItem();
                double valor = Double.parseDouble(txtValor.getText());
                int estoque = Integer.parseInt(txtEstoque.getText());
                
                // neste else chamo o Controller

                boolean retorno = ProdutoController.Novo(produto, categoria, valor, estoque);
                if (retorno == true){
                    JOptionPane.showMessageDialog(null,"Produto cadastrado com sucesso!");
                }

                else{
                    JOptionPane.showMessageDialog(null,"Falha ao cadastrar novo produto!");

                }}

            }
            else{
                //edicao
                //TODO: implementar verificação de obrigatoriedade

                if(txtProduto.getText().trim().equals("") || categoria_verifica.equals("")|| txtValor.getText().trim().equals("")|| txtEstoque.getText().trim().equals("") ){
                    //validando as informacoes
                    //validar se o usuario realmente digitou
                    JOptionPane.showMessageDialog(null,"Voce esqueceu de um dos valores obrigatórios, Por gentileza Preencher.");

                }
                else{
                    //transformando os valores dos campos ems eus determinados valores corretos (tipos)

                    objProduto.setProduto(txtProduto.getText());
                    objProduto.setCategoria(categoria_verifica);
                    objProduto.setPreco(Double.parseDouble(txtValor.getText()));
                    objProduto.setEstoque(Integer.parseInt(txtEstoque.getText()));
                    

                    boolean retorno = ProdutoController.Alterar(objProduto);
                    if (retorno == true){
                        JOptionPane.showMessageDialog(null,"Produto atualizado com sucesso!");
                    }

                    else{
                        JOptionPane.showMessageDialog(null,"Falha ao atualizar produto!");

                    }}

                }

    }//GEN-LAST:event_btnFnCadastroSalvarActionPerformed

    private void btnFnCadastroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnCadastroCancelarActionPerformed
        txtProduto.setText("");
        txtProduto.setBackground(Color.white);

        txtValor.setText("");
        txtValor.setBackground(Color.white);

        txtEstoque.setText("");
        txtEstoque.setBackground(Color.white);


        this.dispose();
    }//GEN-LAST:event_btnFnCadastroCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFnCadastroCancelar;
    private javax.swing.JButton btnFnCadastroSalvar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
